import { useEffect } from 'react';
import { useDashboardStore } from '../store/dashboardStore';

// Theme definitions
const themes = {
  'corsair-dark': {
    '--bg-primary': '#0a0a0c',
    '--bg-secondary': '#111115',
    '--bg-panel': '#16161a',
    '--bg-panel-hover': '#1a1a1f',
    '--bg-card': '#1e1e24',
    '--border-color': '#2a2a32',
    '--text-primary': '#ffffff',
    '--text-secondary': '#a0a0a8',
    '--text-muted': '#606068',
  },
  'midnight-purple': {
    '--bg-primary': '#0d0a14',
    '--bg-secondary': '#141020',
    '--bg-panel': '#1a1528',
    '--bg-panel-hover': '#201a30',
    '--bg-card': '#251e38',
    '--border-color': '#352a4a',
    '--text-primary': '#ffffff',
    '--text-secondary': '#b0a8c8',
    '--text-muted': '#706888',
  },
  'cyber-green': {
    '--bg-primary': '#0a0c0a',
    '--bg-secondary': '#101510',
    '--bg-panel': '#141a14',
    '--bg-panel-hover': '#182018',
    '--bg-card': '#1c241c',
    '--border-color': '#2a3a2a',
    '--text-primary': '#ffffff',
    '--text-secondary': '#a8b8a8',
    '--text-muted': '#607860',
  },
  'sunset-orange': {
    '--bg-primary': '#0c0a08',
    '--bg-secondary': '#151210',
    '--bg-panel': '#1a1614',
    '--bg-panel-hover': '#201c18',
    '--bg-card': '#24201c',
    '--border-color': '#3a322a',
    '--text-primary': '#ffffff',
    '--text-secondary': '#c8b8a8',
    '--text-muted': '#887868',
  },
  'arctic-blue': {
    '--bg-primary': '#080a0c',
    '--bg-secondary': '#0e1215',
    '--bg-panel': '#121820',
    '--bg-panel-hover': '#161c26',
    '--bg-card': '#1a222c',
    '--border-color': '#283040',
    '--text-primary': '#ffffff',
    '--text-secondary': '#a8b8c8',
    '--text-muted': '#607080',
  },
  'rose-gold': {
    '--bg-primary': '#0c0a0a',
    '--bg-secondary': '#151010',
    '--bg-panel': '#1a1416',
    '--bg-panel-hover': '#20181a',
    '--bg-card': '#241c20',
    '--border-color': '#3a2a30',
    '--text-primary': '#ffffff',
    '--text-secondary': '#c8b0b8',
    '--text-muted': '#886870',
  },
  'nord': {
    '--bg-primary': '#2e3440',
    '--bg-secondary': '#3b4252',
    '--bg-panel': '#434c5e',
    '--bg-panel-hover': '#4c566a',
    '--bg-card': '#4c566a',
    '--border-color': '#5e6779',
    '--text-primary': '#eceff4',
    '--text-secondary': '#d8dee9',
    '--text-muted': '#a4afc0',
  },
  'dracula': {
    '--bg-primary': '#282a36',
    '--bg-secondary': '#2d303d',
    '--bg-panel': '#343746',
    '--bg-panel-hover': '#3c3f50',
    '--bg-card': '#44475a',
    '--border-color': '#545772',
    '--text-primary': '#f8f8f2',
    '--text-secondary': '#ccc8df',
    '--text-muted': '#8b87a3',
  },
  'monokai': {
    '--bg-primary': '#1e1f1c',
    '--bg-secondary': '#272822',
    '--bg-panel': '#2f302a',
    '--bg-panel-hover': '#3a3b33',
    '--bg-card': '#3e3d32',
    '--border-color': '#525248',
    '--text-primary': '#f8f8f2',
    '--text-secondary': '#cfcfc2',
    '--text-muted': '#75715e',
  },
  'solarized-dark': {
    '--bg-primary': '#002b36',
    '--bg-secondary': '#073642',
    '--bg-panel': '#0a3d47',
    '--bg-panel-hover': '#0d4a56',
    '--bg-card': '#0f525e',
    '--border-color': '#2b6876',
    '--text-primary': '#fdf6e3',
    '--text-secondary': '#eee8d5',
    '--text-muted': '#839496',
  },
  'tokyo-night': {
    '--bg-primary': '#1a1b26',
    '--bg-secondary': '#1f202b',
    '--bg-panel': '#24252f',
    '--bg-panel-hover': '#292a36',
    '--bg-card': '#2a2b3d',
    '--border-color': '#3b3d57',
    '--text-primary': '#c0caf5',
    '--text-secondary': '#a9b1d6',
    '--text-muted': '#565f89',
  },
  'catppuccin': {
    '--bg-primary': '#1e1e2e',
    '--bg-secondary': '#252536',
    '--bg-panel': '#2c2c3e',
    '--bg-panel-hover': '#323246',
    '--bg-card': '#383850',
    '--border-color': '#45456a',
    '--text-primary': '#cdd6f4',
    '--text-secondary': '#bac2de',
    '--text-muted': '#7f849c',
  },
  'gruvbox': {
    '--bg-primary': '#1d2021',
    '--bg-secondary': '#282828',
    '--bg-panel': '#32302f',
    '--bg-panel-hover': '#3c3836',
    '--bg-card': '#3c3836',
    '--border-color': '#504945',
    '--text-primary': '#ebdbb2',
    '--text-secondary': '#d5c4a1',
    '--text-muted': '#928374',
  },
  'one-dark': {
    '--bg-primary': '#21252b',
    '--bg-secondary': '#282c34',
    '--bg-panel': '#2c313a',
    '--bg-panel-hover': '#333842',
    '--bg-card': '#3a3f4b',
    '--border-color': '#4b5263',
    '--text-primary': '#abb2bf',
    '--text-secondary': '#9da5b4',
    '--text-muted': '#5c6370',
  },
  'ayu-dark': {
    '--bg-primary': '#0a0e14',
    '--bg-secondary': '#0d1219',
    '--bg-panel': '#11161d',
    '--bg-panel-hover': '#151b23',
    '--bg-card': '#1a2029',
    '--border-color': '#273240',
    '--text-primary': '#e6e1cf',
    '--text-secondary': '#c7c3b5',
    '--text-muted': '#5c6773',
  },
  'synthwave': {
    '--bg-primary': '#0f0a1a',
    '--bg-secondary': '#1a1329',
    '--bg-panel': '#241b38',
    '--bg-panel-hover': '#2e2345',
    '--bg-card': '#382a52',
    '--border-color': '#4a3a6a',
    '--text-primary': '#f0e0ff',
    '--text-secondary': '#d0b8e8',
    '--text-muted': '#8868a8',
  },
  'cyberpunk': {
    '--bg-primary': '#0a0a12',
    '--bg-secondary': '#12121e',
    '--bg-panel': '#1a1a2a',
    '--bg-panel-hover': '#222236',
    '--bg-card': '#2a2a42',
    '--border-color': '#3a3a58',
    '--text-primary': '#00fff0',
    '--text-secondary': '#00d4c8',
    '--text-muted': '#008878',
  },
  'cappuccino': {
    '--bg-primary': '#1c1410',
    '--bg-secondary': '#251c16',
    '--bg-panel': '#2e231c',
    '--bg-panel-hover': '#372a22',
    '--bg-card': '#3f3128',
    '--border-color': '#5a483c',
    '--text-primary': '#f5e6d3',
    '--text-secondary': '#d4c4b0',
    '--text-muted': '#8a7a68',
  },
  'matcha': {
    '--bg-primary': '#141810',
    '--bg-secondary': '#1a2016',
    '--bg-panel': '#20281c',
    '--bg-panel-hover': '#263022',
    '--bg-card': '#2c3828',
    '--border-color': '#40503a',
    '--text-primary': '#e8f0e0',
    '--text-secondary': '#c8d8b8',
    '--text-muted': '#7a8a68',
  },
  'ocean-deep': {
    '--bg-primary': '#0a1014',
    '--bg-secondary': '#0e161c',
    '--bg-panel': '#121e28',
    '--bg-panel-hover': '#162632',
    '--bg-card': '#1a2e3c',
    '--border-color': '#284050',
    '--text-primary': '#e0f0f8',
    '--text-secondary': '#b0d0e0',
    '--text-muted': '#608090',
  },
  'cherry-blossom': {
    '--bg-primary': '#140c10',
    '--bg-secondary': '#1c1218',
    '--bg-panel': '#261820',
    '--bg-panel-hover': '#301e28',
    '--bg-card': '#3a2430',
    '--border-color': '#503848',
    '--text-primary': '#ffe8f0',
    '--text-secondary': '#e8c0d0',
    '--text-muted': '#906878',
  },
  'forest': {
    '--bg-primary': '#0c100c',
    '--bg-secondary': '#121812',
    '--bg-panel': '#182018',
    '--bg-panel-hover': '#1e281e',
    '--bg-card': '#243024',
    '--border-color': '#364836',
    '--text-primary': '#e0f0e0',
    '--text-secondary': '#b8d8b8',
    '--text-muted': '#688868',
  },
  'midnight-blue': {
    '--bg-primary': '#0a0c14',
    '--bg-secondary': '#10141e',
    '--bg-panel': '#161c2a',
    '--bg-panel-hover': '#1c2436',
    '--bg-card': '#222c42',
    '--border-color': '#324058',
    '--text-primary': '#e8f0ff',
    '--text-secondary': '#b8c8e8',
    '--text-muted': '#6878a0',
  },
  'volcanic': {
    '--bg-primary': '#100808',
    '--bg-secondary': '#180c0c',
    '--bg-panel': '#221010',
    '--bg-panel-hover': '#2c1414',
    '--bg-card': '#361818',
    '--border-color': '#502828',
    '--text-primary': '#fff0e8',
    '--text-secondary': '#e8c0b0',
    '--text-muted': '#a06858',
  },
  'slate': {
    '--bg-primary': '#101214',
    '--bg-secondary': '#161a1e',
    '--bg-panel': '#1c2228',
    '--bg-panel-hover': '#242c34',
    '--bg-card': '#2c3640',
    '--border-color': '#404c58',
    '--text-primary': '#e8eef4',
    '--text-secondary': '#c0ccd8',
    '--text-muted': '#707c88',
  },
  'lavender': {
    '--bg-primary': '#100e14',
    '--bg-secondary': '#18141e',
    '--bg-panel': '#201a28',
    '--bg-panel-hover': '#282032',
    '--bg-card': '#30263c',
    '--border-color': '#463a58',
    '--text-primary': '#f0e8ff',
    '--text-secondary': '#d0c0e8',
    '--text-muted': '#806898',
  },
  'copper': {
    '--bg-primary': '#12100c',
    '--bg-secondary': '#1a1610',
    '--bg-panel': '#241e16',
    '--bg-panel-hover': '#2e261c',
    '--bg-card': '#382e22',
    '--border-color': '#504438',
    '--text-primary': '#fff0e0',
    '--text-secondary': '#e0c8a8',
    '--text-muted': '#907858',
  },
  'emerald': {
    '--bg-primary': '#0a100c',
    '--bg-secondary': '#0e1810',
    '--bg-panel': '#122016',
    '--bg-panel-hover': '#16281a',
    '--bg-card': '#1a3020',
    '--border-color': '#284830',
    '--text-primary': '#e0fff0',
    '--text-secondary': '#a8e8c0',
    '--text-muted': '#588868',
  },
  'carbon': {
    '--bg-primary': '#0c0c0c',
    '--bg-secondary': '#141414',
    '--bg-panel': '#1c1c1c',
    '--bg-panel-hover': '#242424',
    '--bg-card': '#2c2c2c',
    '--border-color': '#404040',
    '--text-primary': '#f0f0f0',
    '--text-secondary': '#c8c8c8',
    '--text-muted': '#707070',
  },
  'bubblegum': {
    '--bg-primary': '#140a14',
    '--bg-secondary': '#1e101e',
    '--bg-panel': '#281628',
    '--bg-panel-hover': '#321c32',
    '--bg-card': '#3c223c',
    '--border-color': '#583458',
    '--text-primary': '#ffe8ff',
    '--text-secondary': '#e8b8e8',
    '--text-muted': '#986898',
  },
  'teal': {
    '--bg-primary': '#0a1212',
    '--bg-secondary': '#0e1a1a',
    '--bg-panel': '#122222',
    '--bg-panel-hover': '#162a2a',
    '--bg-card': '#1a3232',
    '--border-color': '#284848',
    '--text-primary': '#e0ffff',
    '--text-secondary': '#a8e8e8',
    '--text-muted': '#588888',
  },
};

// Font definitions with size scaling for different fonts
const fonts = {
  tech: {
    '--font-display': "'Orbitron', sans-serif",
    '--font-body': "'Rajdhani', sans-serif",
    '--font-mono': "'Share Tech Mono', monospace",
    '--clock-size': '64px',
    '--clock-seconds-size': '32px',
    '--clock-date-size': '16px',
  },
  modern: {
    '--font-display': "'Inter', sans-serif",
    '--font-body': "'Inter', sans-serif",
    '--font-mono': "'JetBrains Mono', monospace",
    '--clock-size': '64px',
    '--clock-seconds-size': '32px',
    '--clock-date-size': '16px',
  },
  classic: {
    '--font-display': "'Roboto', sans-serif",
    '--font-body': "'Roboto', sans-serif",
    '--font-mono': "'Roboto Mono', monospace",
    '--clock-size': '64px',
    '--clock-seconds-size': '32px',
    '--clock-date-size': '16px',
  },
  gaming: {
    '--font-display': "'Press Start 2P', cursive",
    '--font-body': "'VT323', monospace",
    '--font-mono': "'VT323', monospace",
    '--clock-size': '28px',
    '--clock-seconds-size': '16px',
    '--clock-date-size': '12px',
  },
  futuristic: {
    '--font-display': "'Audiowide', cursive",
    '--font-body': "'Exo 2', sans-serif",
    '--font-mono': "'Fira Code', monospace",
    '--clock-size': '56px',
    '--clock-seconds-size': '28px',
    '--clock-date-size': '15px',
  },
  minimal: {
    '--font-display': "'Space Grotesk', sans-serif",
    '--font-body': "'Space Grotesk', sans-serif",
    '--font-mono': "'Space Mono', monospace",
    '--clock-size': '68px',
    '--clock-seconds-size': '34px',
    '--clock-date-size': '16px',
  },
  terminal: {
    '--font-display': "'IBM Plex Mono', monospace",
    '--font-body': "'IBM Plex Mono', monospace",
    '--font-mono': "'IBM Plex Mono', monospace",
    '--clock-size': '52px',
    '--clock-seconds-size': '26px',
    '--clock-date-size': '14px',
  },
  elegant: {
    '--font-display': "'Playfair Display', serif",
    '--font-body': "'Source Sans Pro', sans-serif",
    '--font-mono': "'Source Code Pro', monospace",
    '--clock-size': '60px',
    '--clock-seconds-size': '30px',
    '--clock-date-size': '16px',
  },
  retro: {
    '--font-display': "'Russo One', sans-serif",
    '--font-body': "'Titillium Web', sans-serif",
    '--font-mono': "'Inconsolata', monospace",
    '--clock-size': '58px',
    '--clock-seconds-size': '29px',
    '--clock-date-size': '15px',
  },
  clean: {
    '--font-display': "'Poppins', sans-serif",
    '--font-body': "'Poppins', sans-serif",
    '--font-mono': "'Cascadia Code', monospace",
    '--clock-size': '62px',
    '--clock-seconds-size': '31px',
    '--clock-date-size': '16px',
  },
  neon: {
    '--font-display': "'Monoton', cursive",
    '--font-body': "'Quicksand', sans-serif",
    '--font-mono': "'Fira Code', monospace",
    '--clock-size': '48px',
    '--clock-seconds-size': '24px',
    '--clock-date-size': '14px',
  },
  digital: {
    '--font-display': "'DSEG7 Classic', 'Orbitron', sans-serif",
    '--font-body': "'Rajdhani', sans-serif",
    '--font-mono': "'Share Tech Mono', monospace",
    '--clock-size': '60px',
    '--clock-seconds-size': '30px',
    '--clock-date-size': '14px',
  },
  luxury: {
    '--font-display': "'Cinzel', serif",
    '--font-body': "'Cormorant Garamond', serif",
    '--font-mono': "'Courier Prime', monospace",
    '--clock-size': '58px',
    '--clock-seconds-size': '29px',
    '--clock-date-size': '16px',
  },
  industrial: {
    '--font-display': "'Bebas Neue', sans-serif",
    '--font-body': "'Barlow', sans-serif",
    '--font-mono': "'Ubuntu Mono', monospace",
    '--clock-size': '72px',
    '--clock-seconds-size': '36px',
    '--clock-date-size': '16px',
  },
  handwritten: {
    '--font-display': "'Permanent Marker', cursive",
    '--font-body': "'Patrick Hand', cursive",
    '--font-mono': "'Indie Flower', cursive",
    '--clock-size': '56px',
    '--clock-seconds-size': '28px',
    '--clock-date-size': '18px',
  },
  scifi: {
    '--font-display': "'Michroma', sans-serif",
    '--font-body': "'Electrolize', sans-serif",
    '--font-mono': "'Nova Mono', monospace",
    '--clock-size': '52px',
    '--clock-seconds-size': '26px',
    '--clock-date-size': '14px',
  },
  newspaper: {
    '--font-display': "'Playfair Display SC', serif",
    '--font-body': "'Libre Baskerville', serif",
    '--font-mono': "'Cutive Mono', monospace",
    '--clock-size': '54px',
    '--clock-seconds-size': '27px',
    '--clock-date-size': '16px',
  },
  rounded: {
    '--font-display': "'Nunito', sans-serif",
    '--font-body': "'Nunito Sans', sans-serif",
    '--font-mono': "'Cousine', monospace",
    '--clock-size': '64px',
    '--clock-seconds-size': '32px',
    '--clock-date-size': '16px',
  },
  sharp: {
    '--font-display': "'Saira', sans-serif",
    '--font-body': "'Saira Condensed', sans-serif",
    '--font-mono': "'Saira Mono', monospace",
    '--clock-size': '66px',
    '--clock-seconds-size': '33px',
    '--clock-date-size': '15px',
  },
  athletic: {
    '--font-display': "'Anton', sans-serif",
    '--font-body': "'Oswald', sans-serif",
    '--font-mono': "'Overpass Mono', monospace",
    '--clock-size': '70px',
    '--clock-seconds-size': '35px',
    '--clock-date-size': '16px',
  },
  typewriter: {
    '--font-display': "'Special Elite', cursive",
    '--font-body': "'Courier Prime', monospace",
    '--font-mono': "'Courier Prime', monospace",
    '--clock-size': '50px',
    '--clock-seconds-size': '25px',
    '--clock-date-size': '14px',
  },
  geometric: {
    '--font-display': "'Comfortaa', cursive",
    '--font-body': "'Quicksand', sans-serif",
    '--font-mono': "'Anonymous Pro', monospace",
    '--clock-size': '60px',
    '--clock-seconds-size': '30px',
    '--clock-date-size': '16px',
  },
  condensed: {
    '--font-display': "'Fjalla One', sans-serif",
    '--font-body': "'Open Sans Condensed', sans-serif",
    '--font-mono': "'Roboto Mono', monospace",
    '--clock-size': '74px',
    '--clock-seconds-size': '37px',
    '--clock-date-size': '16px',
  },
  friendly: {
    '--font-display': "'Baloo 2', cursive",
    '--font-body': "'Varela Round', sans-serif",
    '--font-mono': "'Oxygen Mono', monospace",
    '--clock-size': '58px',
    '--clock-seconds-size': '29px',
    '--clock-date-size': '16px',
  },
};

// Accent color generates glow variations
const getAccentVars = (color) => {
  // Parse hex to RGB
  const hex = color.replace('#', '');
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  // Slightly darker secondary
  const darken = (val) => Math.max(0, Math.round(val * 0.8));

  return {
    '--accent-primary': color,
    '--accent-secondary': `rgb(${darken(r)}, ${darken(g)}, ${darken(b)})`,
    '--accent-glow': `rgba(${r}, ${g}, ${b}, 0.15)`,
    '--accent-glow-strong': `rgba(${r}, ${g}, ${b}, 0.3)`,
    '--border-glow': `rgba(${r}, ${g}, ${b}, 0.2)`,
  };
};

export function useTheme() {
  const { settings } = useDashboardStore();
  const { theme, accentColor, fontStyle } = settings;

  useEffect(() => {
    const root = document.documentElement;

    // Apply theme colors
    const themeVars = themes[theme] || themes['corsair-dark'];
    Object.entries(themeVars).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });

    // Apply accent color
    const accentVars = getAccentVars(accentColor || '#00d4ff');
    Object.entries(accentVars).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });

    // Apply font style
    const fontVars = fonts[fontStyle] || fonts['tech'];
    Object.entries(fontVars).forEach(([key, value]) => {
      root.style.setProperty(key, value);
    });

  }, [theme, accentColor, fontStyle]);
}

export default useTheme;
